//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFramework.GenCodeTool.Resources.Lan {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenCodeToolResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenCodeToolResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NFramework.GenCodeTool.Resources.Lan.GenCodeToolResource", typeof(GenCodeToolResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All Column 的本地化字符串。
        /// </summary>
        public static string AllColumn {
            get {
                return ResourceManager.GetString("AllColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Tables 的本地化字符串。
        /// </summary>
        public static string AllTable {
            get {
                return ResourceManager.GetString("AllTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeType 的本地化字符串。
        /// </summary>
        public static string CodeType {
            get {
                return ResourceManager.GetString("CodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ColumnId 的本地化字符串。
        /// </summary>
        public static string ColumnId {
            get {
                return ResourceManager.GetString("ColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Name 的本地化字符串。
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment 的本地化字符串。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect Database 的本地化字符串。
        /// </summary>
        public static string ConnectDB {
            get {
                return ResourceManager.GetString("ConnectDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect Database Failed 的本地化字符串。
        /// </summary>
        public static string ConnectDBFaild {
            get {
                return ResourceManager.GetString("ConnectDBFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConnectionString 的本地化字符串。
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBType 的本地化字符串。
        /// </summary>
        public static string DBType {
            get {
                return ResourceManager.GetString("DBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DefaultValue 的本地化字符串。
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Columns Failed 的本地化字符串。
        /// </summary>
        public static string Error_GetColumn {
            get {
                return ResourceManager.GetString("Error_GetColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Tables Failed 的本地化字符串。
        /// </summary>
        public static string Error_GetTable {
            get {
                return ResourceManager.GetString("Error_GetTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required Connection String 的本地化字符串。
        /// </summary>
        public static string Error_NoConnectionString {
            get {
                return ResourceManager.GetString("Error_NoConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required Select DB Type 的本地化字符串。
        /// </summary>
        public static string Error_NoDBInfoGetter {
            get {
                return ResourceManager.GetString("Error_NoDBInfoGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Table less than one 的本地化字符串。
        /// </summary>
        public static string Error_NoGenTable {
            get {
                return ResourceManager.GetString("Error_NoGenTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required namespace 的本地化字符串。
        /// </summary>
        public static string Error_NoNamespace {
            get {
                return ResourceManager.GetString("Error_NoNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required project name 的本地化字符串。
        /// </summary>
        public static string Error_NoProjectName {
            get {
                return ResourceManager.GetString("Error_NoProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required setting name 的本地化字符串。
        /// </summary>
        public static string Error_NoSettingName {
            get {
                return ResourceManager.GetString("Error_NoSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required target path 的本地化字符串。
        /// </summary>
        public static string Error_NoTargetPath {
            get {
                return ResourceManager.GetString("Error_NoTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required template path 的本地化字符串。
        /// </summary>
        public static string Error_NoTemplatePath {
            get {
                return ResourceManager.GetString("Error_NoTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required Select Code Type 的本地化字符串。
        /// </summary>
        public static string Error_NullCodeGetter {
            get {
                return ResourceManager.GetString("Error_NullCodeGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error_NullDBGetter 的本地化字符串。
        /// </summary>
        public static string Error_NullDBGetter {
            get {
                return ResourceManager.GetString("Error_NullDBGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error_NullProjectInfo 的本地化字符串。
        /// </summary>
        public static string Error_NullProjectInfo {
            get {
                return ResourceManager.GetString("Error_NullProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error_OpenDB 的本地化字符串。
        /// </summary>
        public static string Error_OpenDB {
            get {
                return ResourceManager.GetString("Error_OpenDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish 的本地化字符串。
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FK Column 的本地化字符串。
        /// </summary>
        public static string FKColumnName {
            get {
                return ResourceManager.GetString("FKColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FK Name 的本地化字符串。
        /// </summary>
        public static string FKName {
            get {
                return ResourceManager.GetString("FKName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FK Table 的本地化字符串。
        /// </summary>
        public static string FKTableName {
            get {
                return ResourceManager.GetString("FKTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Code Faild 的本地化字符串。
        /// </summary>
        public static string GenFaild {
            get {
                return ResourceManager.GetString("GenFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating 的本地化字符串。
        /// </summary>
        public static string GenProgress {
            get {
                return ResourceManager.GetString("GenProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Code Successfully 的本地化字符串。
        /// </summary>
        public static string GenSucc {
            get {
                return ResourceManager.GetString("GenSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GenTargetPath 的本地化字符串。
        /// </summary>
        public static string GenTargetPath {
            get {
                return ResourceManager.GetString("GenTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsAutoNum 的本地化字符串。
        /// </summary>
        public static string IsAutoNum {
            get {
                return ResourceManager.GetString("IsAutoNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsClearTarget 的本地化字符串。
        /// </summary>
        public static string IsClearTarget {
            get {
                return ResourceManager.GetString("IsClearTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsFK 的本地化字符串。
        /// </summary>
        public static string IsFK {
            get {
                return ResourceManager.GetString("IsFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsGen 的本地化字符串。
        /// </summary>
        public static string IsGen {
            get {
                return ResourceManager.GetString("IsGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsGenUI 的本地化字符串。
        /// </summary>
        public static string IsGenUI {
            get {
                return ResourceManager.GetString("IsGenUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsInput 的本地化字符串。
        /// </summary>
        public static string IsInput {
            get {
                return ResourceManager.GetString("IsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsNullable 的本地化字符串。
        /// </summary>
        public static string IsNullable {
            get {
                return ResourceManager.GetString("IsNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsPK 的本地化字符串。
        /// </summary>
        public static string IsPK {
            get {
                return ResourceManager.GetString("IsPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gen Search Condition 的本地化字符串。
        /// </summary>
        public static string IsSearchCondition {
            get {
                return ResourceManager.GetString("IsSearchCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gen Search Result 的本地化字符串。
        /// </summary>
        public static string IsSearchResult {
            get {
                return ResourceManager.GetString("IsSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsUnique 的本地化字符串。
        /// </summary>
        public static string IsUnique {
            get {
                return ResourceManager.GetString("IsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxLength 的本地化字符串。
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Value 的本地化字符串。
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min Value 的本地化字符串。
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Namespace 的本地化字符串。
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Precision 的本地化字符串。
        /// </summary>
        public static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProjectDisplayName 的本地化字符串。
        /// </summary>
        public static string ProjectDisplayName {
            get {
                return ResourceManager.GetString("ProjectDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProjectName 的本地化字符串。
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReferenceFolder 的本地化字符串。
        /// </summary>
        public static string ReferenceFolder {
            get {
                return ResourceManager.GetString("ReferenceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SavedSettings 的本地化字符串。
        /// </summary>
        public static string SavedSettings {
            get {
                return ResourceManager.GetString("SavedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Setting 的本地化字符串。
        /// </summary>
        public static string SaveGenSetting {
            get {
                return ResourceManager.GetString("SaveGenSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale 的本地化字符串。
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting Name 的本地化字符串。
        /// </summary>
        public static string SettingName {
            get {
                return ResourceManager.GetString("SettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting Save Faild 的本地化字符串。
        /// </summary>
        public static string SettingSaveFaild {
            get {
                return ResourceManager.GetString("SettingSaveFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting Save Successfully 的本地化字符串。
        /// </summary>
        public static string SettingSaveSucc {
            get {
                return ResourceManager.GetString("SettingSaveSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL Type 的本地化字符串。
        /// </summary>
        public static string SqlType {
            get {
                return ResourceManager.GetString("SqlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Generate 的本地化字符串。
        /// </summary>
        public static string StartGen {
            get {
                return ResourceManager.GetString("StartGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Name 的本地化字符串。
        /// </summary>
        public static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TemplatePath 的本地化字符串。
        /// </summary>
        public static string TemplatePath {
            get {
                return ResourceManager.GetString("TemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ViewFolder 的本地化字符串。
        /// </summary>
        public static string ViewFolder {
            get {
                return ResourceManager.GetString("ViewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
